### ISSUE TITLE
Unbound record field state, seemingly wrong & unexpected? 

### ISSUE THREAD

**Issue by fxfactorial** [reasonml/reason-react#150]
Say our code is:

```javascript
let profile = ReasonReact.reducerComponent("Profile");

let s = ReasonReact.stringToElement;

let make = (children) => {
  ...profile,
  initialState: fun () => ([]: list(string)),
  reducer: (_, _) => ReasonReact.NoUpdate,
  render: (type f, self) => {
    let []: list(f) = self.state;
    <div> <p> (s("Hello world")) </p> </div>
  }
};
```

This errors out with: 
```

   8 ┆ reducer: (_, _) => ReasonReact.NoUpdate,
   9 ┆ render: (type f, self) => {
  10 ┆   let []: list(f) = self.state;
  11 ┆   <div> <p> (s("Hello world")) </p> </div>
  12 ┆ }

  Unbound record field state

ninja: build stopped: subcommand failed.
>>>> Finish compiling(exit: 1)
```

That seems wrong to me.

**Comment by jordwalke** [comment]
It's interesting that this is happening because of the locally abstract type in the lambda. It looks like locally abstract types are throwing off "type directed record field disambiguation" (which is how OCaml uses inferred types to tell which record field you are actually referring to).
I'm fascinated by why locally abstract types might interfere with (type directed record field disambiguation), but I'm also curious why you are using locally abstract types (I've only seen them be very useful with GADTs, and local module definitions)..

**Comment by rickyvetter** [comment]
This cannot happen with the function component API so I'm closing this out.
