### ISSUE TITLE
Transition to react 16

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#199]
Currently quite a chunk of our codebase is rather convoluted, due to the need of supporting react 15. Some of the patterns are also unfriendly to react 16 async mode, especially in sCU where async mode dev mode will trigger sCU twice to discourage you to put side-effects in there.

Supporting just 16 will also allow us to transition toward the same API deprecation strategy as https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

It'll also give us a clearer conscience to implement e.g. context v2. Since it wouldn't yell at runtime that we're binding to nonexistent ReactJS features

**Comment by chenglou** [comment]
@rickyvetter let's start making as many modifications as possible that are still backward-compatible. We can delay the need for requiring 16 just to be nice

**Comment by ckknight** [comment]
I could see value in providing a dedicated (possibly frozen) branch of `reason-react` that supports React 15, but given that both mainline React and React-Native are on React 16 now, that's where the focus of `reason-react` should lie.

**Comment by joefiorini** [comment]
I’ve seen it said a couple times (and it’s even on the Reason React homepage “Playground for future React”) that RR represents the future of React. Given that premise, I would never expect it to support anything but the latest React. Why is the support for 15 such a strong consideration if this is supposed to represent the future?

**Comment by AdamBrodzinski** [comment]
@joefiorini They have plans of migrating to v16, it's just a matter of when. Sprinkled in the docs you'll see notes like "do this that way so you'll have an easier transition to Fibers (v16).

**Comment by chenglou** [comment]
We already support 16, just not the newest APIs, since they're still unstable and even reactjs is still debating about it. We'll first start by supporting the stable subset. If you'd like to read between the lines, watch out for the next release.

> I would never expect it to support anything but the latest React

We're definitely forward-looking, but that doesn't mean removing support for 15 when there's no reason to. 15 isn't dragging us down

**Comment by AdamBrodzinski** [comment]
Thanks for the update @chenglou ! Do you have a rough ballpark for the new context API? I've been using the react context library in the meantime but it's not quite the same.

**Comment by chenglou** [comment]
Unfortunately, not the context API. This one's still unstable

**Comment by Anahkiasen** [comment]
That's not what the [current docs](https://reactjs.org/docs/context.html) say, they just mention the _legacy_ API will be removed but the current API is stble as far as I know.

**Comment by brad-decker** [comment]
@anahkiasen anything this new is subject to change under the hood even if the signature remains the same to avoid breaking. Speaking from personal experience the context api is great but it doesn’t interweave with every tool out there. Next js currently has an issue where context initializers can be spread throughout multiple bundles causing render mismatches between server and client. 

I appreciate the caution in rolling this out to reason react it means that when we do get it the details of its implementation will be less worrisome and stable enough to trust it. 

The docs for the context api are geared towards not discouraging its use but it can and will likely change as they work through it. Just look at string refs which wasn’t a “unsafe” practice. Then we had refs by function and now a whole new ref api. All the improvements are awesome but there are levels of stability that come from time, use and working through the patterns that get implemented in user land.

The context api docs didn’t have an example of updating the context from a deeply nested component in its original version, but it was in almost every user land blog post I read. The recommended pattern included, at that time, spreading your state into the value prop and adding your update methods. Of course we now know thanks to the rigor of the react maintainers  that this ALWAYS triggers a rerendee of consumers on state update because Equality checks were first done by reference.

Anyways, sorry for the book! I’m looking forward to using the context api as we start transitioning our stack to include reason, but I want to make sure it’s the right approach to solve the problem of sharing state between nested trees of components.

**Comment by farism** [comment]
@brad-decker I mostly agree with you but if you take the example you gave of refs having changed twice, that would indicate nothing is really ever "stable". Unless otherwise stated it will never change, which is unlikely for anyone to claim. 

So how to determine when to support it? When is something stable? Is this based on internal FB conversations? Is there a specific period of time that must elapse before something is considered stable?

You would think with having the old context API existing for so long and then finally coming out with a new context API, that they would have taken the time/consideration this second iteration to be relatively stable. But who knows.

I'm mostly asking because my team is working on a UI library and we are already diving fairly deep into the new context APIs, which I'm now a little worried about 😅

**Comment by chenglou** [comment]
> Is this based on internal FB conversations?

Yes, though please don’t quote me on this matter. 

We _will_ release support for Fragment next release though.

**Comment by farism** [comment]
Cool! That's great to hear Fragments are coming.

And I didn't mean to sound impatient about the other features; they aren't blocking me in any way. Thanks for all the hard work and communication.

**Comment by rickyvetter** [comment]
We are on latest React now. If there are any specific features missing please create an issue for them!
