### ISSUE TITLE
Better way of constraining rerenders

### ISSUE THREAD

**Issue by conartist6** [reasonml/reason-react#200]
Reason has built in immutable data types, so it seems like ReasonReact should be able to understand that when a component's props are all immutable a rerender can be saved when the all input props have reference equality. 

Since Reason erases type information, though, it seems like this would require support from Reason itself.

**Comment by aij** [comment]
Doesn't React already avoid such re-renders, even in JS when the props are mutable and mutated?

**Comment by conartist6** [comment]
It doesn't avoid running the render method. If the virtual DOM is not different from the last run's virtual DOM though, it avoids touching the actual DOM.

It is orders of magnitude faster to avoid running every render method (and the reconciler) if shallow equality can tell you if your props are the same.

The biggest difference though is that == can short circuit a whole component tree's worth of work, whereas without any shouldComponentUpdate logic every subcomponent (recursively) of a component whose state has changed must also run its render.

**Comment by AriaFallah** [comment]
@cknitt having read through the code, I don't think there's a way to do that right now because props aren't retained and the retainedProps API is deprecated. @chenglou mentioned that they might be turning props back into a data structure in the long term, which would fix this issue, and moreover he said @rickyvetter is working on adding the getDerivedStateFromProps lifecycle soon to at least make life a bit easier in the meantime.

**Comment by Anahkiasen** [comment]
In the meantime should [this page](https://reasonml.github.io/reason-react/docs/en/lifecycles) be updated with some informations? It currently does not mention that all the retained props API is deprecated and doesn't show you what is the current way to do it either :/

**Comment by rickyvetter** [comment]
`React.pure` is now supported in the hooks api.
