### ISSUE TITLE
<input type="range" /> value is sometimes a string but it still types as an int

### ISSUE THREAD

**Issue by jessep** [reasonml/reason-react#212]
I'm getting an int from a range input. I'm getting a runtime error where if `theInt`, which comes from the range input is 20, then `theInt + 10` in ReasonML is `2010`, but it should be `30` so it is acting like string concatenation instead of integer addition. 

I made a video showing the issue  https://cl.ly/0D0r0W1j3p3p

I'm currently working around this in the following way:
```
    let makeSureIsInt: int => int = [%raw
      {|function(thing){ return parseInt(thing) }|}
    ];
    let minLineSpacing = makeSureIsInt(self.state.fontSize) + 10;

```

**Comment by jessep** [comment]
Also seems like I can use valueAsNumber (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range).

**Comment by mmiszy** [comment]
@jessep `HTMLInputElement.value` is always a string according to the HTML specification. That means there's a type error somewhere in your code.
Reason doesn't catch that bug because `ReactDOMRe.domElementToObj` returns `Js.t({..})` type (which could contain anything).

I agree this is suboptimal and I'm looking forward for better (typed) DOM API in ReasonReact.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
