### ISSUE TITLE
Type correctness issue

### ISSUE THREAD

**Issue by venil7** [reasonml/reason-react#271]
If i create a minimal `component`

```
type state = {a: int}; //state type defined like this
type action =
  | Remove
  | Add
  | Update;

let component = ReasonReact.reducerComponent("TodoApp");
let make = _children => {
  ...component,
  initialState: () => "hello", // allows me to return initial state that doesn't match my state type..??
  reducer: (_action: action, state: state) => ReasonReact.Update(state), //state type mentioned here too
  render: _self => <div> <ul /> </div>,
};
```
have a look at line around initialState, I'm introducing inconsistent state type
surprisingly my code compiles, how is this possible?

```
>>>> Start compiling
[2/2] Building src/TodoApp.mlast.d
[1/1] Building src/TodoApp-ReactTemplate.cmj
>>>> Finish compiling
```

**Comment by cristianoc** [comment]
“type state” just defines a type called “state”. You can still use another type for the component state, in this case string.

**Comment by cristianoc** [comment]
An inconsistency would be the initial state being of different type than the state used in the reducer, or in the render function.

In the example, just rename “type state = ...” with “type unused = ...”. Then it should be clear why a type error is not given.

**Comment by flash-gordon** [comment]
@cristianoc but the reducer is annotated with the `state` type, that is it's actually in use:
```
reducer: (_action: action, state: state)
```

**Comment by cristianoc** [comment]
Sorry for overlooking the explicit `state` annotation.

Now the explanation will really become meh, but here it goes.
For technical reasons, there are two types `componentSpec` and `component`. Only `component` forces the type of initial state to be the same as the state for reducer+render.
So if one adds an explicit annotation `let make = _children : ReasonReact.component(_,_,_) =>`, or uses the component anywhere, e.g. `<Component> </Component>`, then a type error appears.

(The technical reasons are in order to allow the same mechanism to support both stateless components and reducer components, where the former have a default initial state of type unit. Using two different state types in `componentSpec` allows one to override the default `initialState` in case of reducer components).

**Comment by cristianoc** [comment]
Feel free to reopen if there are more questions.
