### ISSUE TITLE
Component children warning

### ISSUE THREAD

**Issue by cxa** [reasonml/reason-react#28]
```reason
let comp = ReasonReact.statelessComponent "Container";

let make children => {
  ...comp,
  render: fun _ => <div> (children |> ReasonReact.arrayToElement) </div>
};
```

Will raise

```
Warning: Each child in an array or iterator should have a unique "key" prop.
```

in Chrome console.

**Comment by dcalhoun** [comment]
I've run into this as well. [Here is a simple test case](https://astrada.github.io/reason-react-playground/?reason=LYewJgrgNgpgBAYQBYEspjgXjgbwFBxywAucAxiMAA4gB2Mtp2ASjAIYDOdrbZxAdB2JtiMWBw4JKNeowAUAImRowCgJQBuAkRilgbANbxscgH602wGAC44QgE4paAcwA0cAPplU6ewzVYAHy42oT84RTUdAzErqFwfrRgMPa2ch4cYgBmAZjBADxIAIzBcjxctDx8gsSOLgAqIACisFbyCgASYlAg7gpwANQDcBZWg8MKAITqAfkA9MWB2gC+Wqt4eKCQsHAACmyJTCGEJOTS0YxYcOXc7NVCImIwElJRssSK+4fqWie6cPojFc5N4VIlcsF8IQwhFzu84tCEgxkqk4OlMlAckE4PkwCgAG6lG6VO4CA72NgAT0aLRgbQ+oN8-lmczxhJWay0m3A0HgUkYbCcKSuUJ0pEiMhiV2JVQED1E4kkcJiin5wiF9h+2lOgOMaMZYHB2NFMP4EousXiiRRaQy2QhOLZS0RhHyXxizpdruU6BGlhgmAUACkQEhaP05p6vfkfRhRgGFAAhEAAIwjUeh83djAz8ydHLw6zwsoAIgB5ACyrH41pSNNaMQA6ihiEgAJJgOQxujq+j2OCRvpUPz4lAwADuPyAA). The browser console displays the error.

Is this a valid bug or should I be defining keys for each child that is passed into a component?

**Comment by chenglou** [comment]
@dcalhoun see here: https://reasonml.github.io/reason-react/docs/en/children.html#pitfall

**Comment by Enalmada** [comment]
@chenglou Is that link still good?  I am a new user trying to learn how to just include children properly and I see nothing in reason-react children docs about "pitfall".  I got here with a google search for the same error 'Each child in an array or iterator should have a unique "key" prop'.  Here is what I hacked together as a solution that might help others landing here for same issue:

Fragment.re ([link](https://github.com/reasonml/reason-react/pull/126#issuecomment-375629706))
`
[@bs.module "react"] external reactClass: ReasonReact.reactClass = "Fragment";
let make = children => ReasonReact.wrapJsForReason(~reactClass, ~props=Js.Obj.empty(), children);
`

Then use it in your HOC like this
`<Fragment> ...children </Fragment>`

Full example:
```
let make = (~children) => {
  ...component,
  render: _self => 
   <Layout>
      <Header/>
      <Fragment> ...children </Fragment>
      <Footer/>
   </Layout>,
};

let default = ReasonReact.wrapReasonForJs(~component, jsProps => make(~children = jsProps##children));
```

(If this looks good then I suggest putting it on the bottom of the reason-react children page because from the perspective of a totally new user, it is surprisingly hard to figure out the right way to pass children without key errors, or "expression has type ‘a array but an expression was expected of type ReasonReact.reactElement" errors.)

**Comment by homanchou** [comment]
I think I managed to successfully quiet my warning.  Here was the mistake I made, (I'm putting this comment here in case it helps someone else).

When I saw the `Warning: Each child in an array or iterator should have a unique "key" prop.` I first tried adding the key property on my `<li key=index>...</li>` where I was passing index in as a prop to my make function.  Apparently this is a common mistake and the React docs talk about this incorrect placement of key.  https://reactjs.org/docs/lists-and-keys.html#keys

Apparently React wants a unique key on the custom component itself, not on the internals of the component e.g:
```
// ************************************************
// The wrong way ....
// ************************************************

// Wrong! There is no need to specify the key here:
function ListItem(props) {
    <li key={value.toString()}>
      {value}
    </li>
}
// Wrong! The key should have been specified here:
    <ListItem value={number} />

// ************************************************
// And the following is the right way....
// ************************************************

function ListItem(props) {
  // Correct! There is no need to specify the key here:
  return <li>{props.value}</li>;
}

// Correct! Key should be specified inside the array.
    <ListItem key={number.toString()}
              value={number} />
```

So in ReasonReact just specify a key on the JSX of your custom component, key and ref will be lifted out of the props and not passed to your make function.

https://github.com/reasonml/reason-react/blob/master/docs/jsx.md#capitalized

This works for me:
```
    <ul>
          {
            ReasonReact.array(
              List.map(
                (invoice: Invoice.t) => <Invoice invoice key={invoice.id} />,
                invoices,
              )
              |> Array.of_list,
            )
          }
   </ul>
```

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
