### ISSUE TITLE
Just unit externals

### ISSUE THREAD

**Issue by rickyvetter** [reasonml/reason-react#370]
Doesn't parse:

[@bs.module "foo"][@react.component]
external svg: () => React.element = "";

Does:

[@bs.module "foo"][@react.component]
external svg: _ => React.element = "";

**Comment by alexfedoseev** [comment]
I believe it should be

```reason
[@bs.module "foo"][@react.component]
external svg: unit => React.element = "";
```

**Comment by rickyvetter** [comment]
lol got me. thanks.

**Comment by IwanKaramazow** [comment]
We should desugar `()` to `unit` in the type language.

**Comment by anmonteiro** [comment]
@IwanKaramazow my personal opinion is that's too much sugar. `()` is a value, `unit` is the type. I think it's important to make this distinction.

**Comment by IwanKaramazow** [comment]
Why do you want to keep the distinction? What about patterns?

**Comment by anmonteiro** [comment]
Well values are allowed in patterns, they’re not types. 

It just feels weird to me to see a value in a type declaration.

It’s exactly the same as allowing the following:

`let foo: 3 -> string`

`3` is a valid pattern, but it’s type is `int`. Just because `()` is the only value that satisfies the type unit, it shouldn’t be treated specially, IMO. It also brings the question of whether this should then be allowed:


```js
type foo = | OnlyValueInVariant

let fn: OnlyValueInVariant -> string
```

**Comment by cknitt** [comment]
I must say that I find myself writing `()` instead of `unit` quite often, but I never write something like

```re
let foo: 3 => string;
```

I think it would make things easier, especially for beginners, if `()` was allowed in the type language, too.

Also, there is a precedent in Haskell and Rust, and Swift allows both `Void` and `()` (see https://en.wikipedia.org/wiki/Unit_type).
