### ISSUE TITLE
Maybe let's make a better `useState`?

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason-react#402]
I've got this at the top of my files, because `useState` is so cumbersome in the "fully type safe" case. Would it make sense to upstream? I know y'all are excited about having `React.re` have no runtime cost, so maybe it could go in `ReasonReact`, and we can `[@@deprecated]` the `React.useState` to avoid confusion?
```
let useState = (initial) => {
  React.useReducer((_ignored, newState) => newState, initial);
};
```

**Comment by justgage** [comment]
I kind of wish there was a `useState` that works like the normal one in React, then a `useStateFn`that does what the current one does. It would be easy to write an upgrade script to help with that. Naturally it would be easy to write the `useState` in terms of the `useStateFn` (the one that currently exists).

**Comment by rickyvetter** [comment]
I think there's definitely a place for a function like this. Going through backlog of other issues/PRs right now but thinking about the right place/way to do this.

PS - so sorry for the horribly slow response here.

**Comment by peterpme** [comment]
Hey @jaredly 

Based on this convo, do you mind opening a PR?

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!

**Comment by erlandsona** [comment]
Sorry to necrobump this but ran into this today helping out my coworkers try and modify some existing ReasonReact code to use local state instead of reductive.

I think that `useState` has to make a choice about which JS signature to support in the external is generally fine. Where we got burnt was that the compiler is unifying the [`Js.t('a)`](https://github.com/reasonml/reason-react/blob/master/src/ReactEvent.re#L17) with the signature of the `setProperty` function returned by `useState` when it should be throwing a compile error.

I see in the documentation there's a comment about returning a `Dom.eventTarget`, curious when that update will land because that'd prevent this issue from happening in the future.

Regarding the Synthetic event issue which in #476 because of unification there's a number of places in code where we've used the setter like `e => e->ReactEvent.Form.target##value->setProperty` which incorrectly unifies the `'a` type parameter which is ultimately just a raw `string` with the `string => string` function the `setProperty` function expects but it works because React ultimately handles both cases.
