### ISSUE TITLE
Why is aria-live commented out?

### ISSUE THREAD

**Issue by mciparelli** [reasonml/reason-react#435]
Why is it commented out? It's a valid attribute

**Comment by johnridesabike** [comment]
It would great if this, and the other `aria` attributes, were fully implemented.

See also: #274 #309 

My guess is that they're commented out because the types for them aren't defined yet. Although having them typed correctly would be nice, it seems like we could just type them as `string` and at least have them usable in some form, even if it's not completely type-safe.

In the meantime, we can always use `ReactDOMRe.createElement`, even if it's tedious.

**Comment by mikaello** [comment]
> So, I guess we're still waiting for a new BuckleScript feature.

This is the BuckleScript issue that is blocking `aria-*`-attributes: [[@bs.string] for bs.deriving abstract ](https://github.com/BuckleScript/bucklescript/issues/2834)

**Comment by peterpme** [comment]
Hey, we're working on merging in the `aria` issues. Please bare with us 😄 

Closing this out for now, thanks!
