### ISSUE TITLE
Confused by compiling

### ISSUE THREAD

**Issue by JoulesZapata** [reasonml/reason-react#467]
Does compiling reason generate JavaScript or compile to JavaScript, 

this
`let isEven = (num: int) => {
    if(num mod 2 == 0){
        "even";
    }else{
        "uneven"
    }
}

Js.log(isEven(3));`

generates this

`'use strict';

function isEven(num) {
  if (num % 2 === 0) {
    return "even";
  } else {
    return "uneven";
  }
}

console.log("uneven");

exports.isEven = isEven;`

is it supposed to just write the answer in the console log? That seems too weird to me

**Comment by pckilgore** [comment]
You have a real compiler now!  The relevant concepts are *constant folding* and *constant propagation*.  

Check out [this example](https://reasonml.github.io/en/try?rrjsx=true&reason=C4TwDgpgBAZgTgVwJbAM4BUD2BRAhsKAXigEEwwAbaAHygCFcA7J3KWgeTiYHMIAoPlQLAIqYADEEjAMbAkmRkSi443IgD4oqAO4ppACwAUK7gEoA3nyhtS5KhqgAiOqIJJFMXBQqOrNhszMDs6uUNr6EIqoALZePn4cXIy8wS5iYRGK7lDAETlwmGBI0qi+AL4CAFKoAHQUmNyGImKSMnIKhmSUEKamANxAA).

Because you call a pure function with a constant, the result with always be the same.  And so the compiler just figures that our for you and inlines the result rather than have to use CPU cycles at run time.  Fun, right?

But github issues probably are not the right place to discuss this.  Checkout the [discord](https://discordapp.com/invite/reasonml), or https://reasonml.chat/
