### ISSUE TITLE
Event type assumption on handlers is not always correct

### ISSUE THREAD

**Issue by acierto** [reasonml/reason-react#47]
Currently when you select something in a dropdown component, reason-react event handler expects to receive "event" object of type reactEventRe to kinda emulate JS event object. *But* third-party library can not always return event object, but just values.
So in JS words, for example
instead of this
`const onClick = (e) => e; `
return 
`const onClick = (e) => e.target.value; `
So then all this assumption on reason-react of getting event type makes it impossible to use without hacks.

Example: 

https://raw.githubusercontent.com/acierto/ts-explorer/master/src/core/advancedFilter/advancedFilter.re lines 28-29.

<img width="723" alt="screen shot 2017-08-12 at 11 51 57" src="https://user-images.githubusercontent.com/2265094/29239712-b777bc52-7f54-11e7-8439-89d9a4304c48.png">

 I'm receiving back from *react-select* lib onChange event with data {value: 'bla', 'label': bla}. But reason-react expects there reactEventRe type. So I don't know another hack as only by means of JS interops map type to my structure. 

<img width="531" alt="screen shot 2017-08-12 at 11 51 47" src="https://user-images.githubusercontent.com/2265094/29239714-bf8462c4-7f54-11e7-930b-6b9bfd829c0c.png">

This project works, so you can easily reproduce that problem there.

**Comment by chenglou** [comment]
It's not constrained to be of type `ReactEventRe.*`. Since you're putting it onto a ReactSelect, whose onChange you've typed as `string => unit` [here](https://github.com/acierto/ts-explorer/blob/a09b6ccd9d91d13e1664414f0ac01c6802c804cb/src/core/components/reactSelect.rei#L5), you should also type handleHasInterfaceTermChange as such.

```reason
let handleHasInterfaceTermChange value {ReasonReact.state: state} => ReasonReact.Update {...state, hasInterfaceTerm: value};
```

aka `onChange` has never been passed an event!

Hope that helps!
