### ISSUE TITLE
Unexpected wrapper function when binding without @react.component

### ISSUE THREAD

**Issue by selenir** [reasonml/reason-react#553]
When you create a binding for component, which doesn't use `[@react.component]` PPX (I think) adds unexpected wrapper function around the make function. E.g.:

```
module SomeComponent {
[@bs.module "some-module"]
  external make:
    {
      .
      "children": React.element,
      "key": Js.undefined(string),
    } =>
    React.element =
    "ExternalComponent";

  [@bs.obj] external makeProps: (~key: string=?, ~children: 'children, unit) => _ = "";
}

<SomeComponent> {React.string("a")} </SomeComponent>
```
Compiles to:
```
React.createElement((function (prim) {
        return SomeModule.ExternalComponent(prim);
      }), {
      children: "a"
    });
```
Expected output:
```
React.createElement(SomeModule.ExternalComponent, {
      children: "a"
    });
```

This makes difference, because if ExternalComponent is a class component, generated code produces runtime error.

**Comment by rickyvetter** [comment]
This should work:

```reason
[@bs.module "some-module"]
  external make:
    React.component({
      .
      "children": React.element,
      "key": Js.undefined(string),
    }) =
    "ExternalComponent";
```

This is a BuckleScript safety feature around function arity. Because we know a little more about how React components specifically work than BuckleScript, we also know that in this case we can safely circumvent this feature. This is also good practice in general as it's possible that `React.component` will eventually be moved to an abstract type.

**Comment by selenir** [comment]
@rickyvetter Got it, thanks!
