### ISSUE TITLE
Docs: Pipe First vs. Pipe Last, What is Pipe to begin with? Even if it points to other docs

### ISSUE THREAD

**Issue by peterpme** [reasonml/reason-react#562]
Pipe First vs. Pipe Last keeps coming up a lot. This is an intermediate question once you're in deep so it's not necessarily geared towards newbies but I'd like some sort of resolve of this 😆

**Comment by Et7f3** [comment]
> What is Pipe to begin with ?

In the unix world: their are a lot of softwares that respect the rule [Do one thing and do it well](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well). It is super useful to write script because each binary can be seen as a function. We could either use subshell `$(ls some_directories)` or use a [pipe `|`](https://en.wikipedia.org/wiki/Pipeline_(Unix)).
In fact this useful pipe is also available in windows shell: cmd.exe and powershell.

Bash and al. use standard stream to pass data. In Reason like almost all programming language we can pass arguments.

> Pipe First vs. Pipe Last

For this it is subject to bikeshed and @jchavarri have explained it in his blog. Others already have explained it. So I won't repeat what they said.
https://www.javierchavarri.com/data-first-and-data-last-a-comparison/

**Comment by davesnx** [comment]
Documenting this should live on Melange (and might point from ReasonReact)
