### ISSUE TITLE
Keep `ReasonReact.update` or provide alt way to update state

### ISSUE THREAD

**Issue by cxa** [reasonml/reason-react#59]
`ReasonReact.update` is deprecated since 0.2.4, and the only way to update non-ref state is `ReasonReact.reduce`. The bad part of `ReasonReact.reduce` is you must define an action, which sometimes is annoying and not neccessary.

**Comment by chenglou** [comment]
You don't need to define an action:

https://cdn.discordapp.com/attachments/235199093155168257/353483185516052480/Screen_Shot_2017-09-02_at_12.14.36_PM.png

We can document this pattern if it proves to have value. But that's basically what `self.update` is.

We can't keep the current incarnation of `self.update` because it's actually not concurrency-safe under ReactJS.
