### ISSUE TITLE
reasonReact router problem

### ISSUE THREAD

**Issue by ChinChuanKuo** [reasonml/reason-react#615]
excute me
If I want to used oauth in golang or other backend
then how to write Router path="/other" component={...} in reasonReact to used other pages

This problem has been stuck for a long time and can't be solved.

**Comment by davesnx** [comment]
We don't have a `<Router />` component in reason-react. 

Closing since there's no enough information to help and it's more like a question than an issue itself.

Feel free to re-open if there's some missing piece on the Router docs that aren't clear: https://reasonml.github.io/reason-react/docs/en/router
