### ISSUE TITLE
[Website] Paragraphs are way too wide.

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-react#79]
Most recommendations put the optimal line length at 45-75 characters (See [this](http://webtypography.net/2.1.2) for example). The line length in the docs are currently about 2-3 times as long at 120+ characters, making it a bit to read.

**Comment by rickyvetter** [comment]
c472c8b90fe8e94c3fb37f285a2ad69fd8744092 brings everything down to the 80-90 chars range. It's a little bit above the ideal but seems to match many other sites in practice (reactjs, alistapart, mdn). Much smaller and the constraint becomes obvious at standard laptop sizes and I'd rather the focus be on the content rather than the style. @glennsl feel free to tweak the constraints in that commit if you think it'd be better to hit a different width.

**Comment by glennsl** [comment]
This looks good to me. Thanks!
